version: '3'

services:
  nginx-rtmp:
    build: .
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
      - STAT_LOCATION=/stat
      - CONTROL_LOCATION=/control
      - RTMP_STREAM_KEY=totallysecretpassword
    volumes:
      - ./certs:/opt/certs
